# Generated by Django 4.0.4 on 2022-07-14 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 4, 57, 18, 664886, tzinfo=utc)),
        ),
    ]
