# Generated by Django 4.0.4 on 2022-07-14 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 4, 58, 32, 937376, tzinfo=utc)),
        ),
    ]
