# Generated by Django 4.0.4 on 2022-06-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full time', 'Full time'), ('Part Time', 'Part Time')], max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('responsibilities', models.TextField()),
                ('no_of_vacancy', models.IntegerField()),
                ('salary', models.FloatField()),
                ('deadline', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
            ],
        ),
    ]
